- hosts: docker
  become: true
  vars:
  - install_directory: /opt/

  - name: "download and install docker"
    apt:
      name: "{{ DOCKER_PACKAGES }} "
      state: present
      force_apt_get: "yes"

  - name: "download and install docker"
    apt:
      name: "{{ DOCKER_PACKAGES }} "
      state: present
      force_apt_get: "yes"

        - name: "install docker"
    apt:
      name: "docker-ce"
      state: present
      force_apt_get: "yes"
