- name: "Install dependecies"
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3
      - python3-pip
  - name: "Add Docker APT key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: "Add Docker APT repo"
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable

  - name: "Install Docker"
    apt: 
     name: docker-ce
     state: latest
     update_cache: true

   - name "Docker service start"
     service:
       name: docker
       state: started

   - name: "Install Docker pip package"
     pip: 
       name: docker     
